### ISSUE TITLE
Error: Address already in use 

### ISSUE THREAD

**Issue by mroberts1** [small-tech/site.js#12]
When I try to launch the site with <site>, I get an address already in use message. I can kill the process using port 80, but is there any way to change the default port used by Site.js?

**Comment by aral** [comment]
Hey Martin,

Not at the moment, no.

One of the goals for Site.js is that is behaves exactly the same way on development as it does on production (including using TLS and forwarding HTTP calls to HTTPS). That said, while it would break functionality to let you override this on the server (since port 80 is used to answer Let’s Encrypt challenges), there is no such drawback to not creating an HTTP server when running on localhost given that it is only used to forward HTTP calls to HTTPS so behaviour is identical to daemon use.

I’ll open an issue to add a flag to allow this (something like --do-not-forward-insecure-requests).

Given my workload, I don’t think this is something I will get to implementing immediately though.

**Comment by aral** [comment]
__Update:__ Internally tracking via [this related issue](https://source.small-tech.org/site.js/app/-/issues/235).
