### ISSUE TITLE
running with existing reverse-proxy possible?

### ISSUE THREAD

**Issue by ccoenen** [small-tech/site.js#14]
I have a server that is running a few projects for me. I would like to also deploy something that uses site.js. At the moment, the most convenient way would be to have site.js do its magic (routing and websockets :-) ) but let the reverse-proxy handle the letsencrypt magic.

So the question is: can site.js be configured to "just" do http/ws with no encrpytion, so that a reverse-proxy can do that part?

**Comment by aral** [comment]
Hi @ccoenen, sorry for the slow reply.

Site.js is purposefully focused on a very specific use case (how to most easily create single-tenant web sites that people can own/control themselves without having to worry about upkeep, etc.) As such, all my effort is going into supporting that use case instead of configurability.

(My eventual goal is that you will be able to hit a website and set up any site/app built with Site.js in under 30 seconds on a server that’s you own/control. Part of that is that there’s an optimised/streamlined setup process that handles everything for you.)

All that said, if that’s something you need, please feel free to fork it and implement it :)
