### ISSUE TITLE
Yunohost integration

### ISSUE THREAD

**Issue by b4D8** [small-tech/site.js#9]
Hi! 

Like [@pedro-nonfree](https://github.com/small-tech/site.js/issues/7), I'd like to have a better understanding of site.js, especially the DotJS thing.

I am thinking I could migrate to site.js but I'd like to do so in a way that's compatible with my current set up with [YunoHost](https://github.com/YunoHost/yunohost) which allows non-developers to easily and securely install [applications](https://yunohost.org/#/apps) on their own servers.

I believe site.js and Yunohost share quite common objectives/philosophy and that bringing site.js to Yunohost could expand your user base. I think this could be done through [packaging site.js as a new app](https://yunohost.org/#/packaging_apps_en) or allowing one to specifically choose services/modules to install.

More precisely, I have a few Hugo-generated static websites that I "deploy" using Yunohost [Custom Web app](https://github.com/YunoHost-Apps/my_webapp_ynh).
This allows me to have a fully working solution (they take care of SSL / Let's encrypt stuff for instance) but I'd like to use site.js integration of Node.js / Express to add dynamic features to my websites (as well as syncing, ephemeral stats etc.)

If that's something you could look into, I'd be glad to contribute somehow.

**Comment by aral** [comment]
Hi @b4D8,

Thank you for your question.

I’m a big fan of Framasoft and YunoHost. YunoHost and Site.js do similar things but while YunoHost is built to host multi-tenant web applications (what you would normally refer to as “web applications” today on the centralised web), Site.js hosts single-tenant web applications (or what I call “Small Web” applications/sites).

As such, the Site.js tool, `site` is equivalent in some ways to the `yunohost` command but with a very different set of features. In order to run Site.js sites on your server, you’d have to have Site.js installed alongside YunoHost and have Site.js serve your Site.js site. I can’t see how this process would integrate with YunoHost itself.

Our next steps with the Site.js/Small Web project is to create a seamless way to create your own single-tenant web sites running Site.js from a web interface and to create some starter applications (like a blog, personal social/messaging site, etc.). As such, that’s where all of our effort is going right now (we’re just two people) and this falls outside the scope of development.

Thank you again for taking the time to explain your use case and for your feedback. I appreciate it.

**Comment by b4D8** [comment]
Hi @aral,

Thanks for your answer and detailed explanation.

While I understand your roadmap which makes a lot of sense (and I will follow those developments with excitement), I'm not quite sure to get why those 2 projects couldn't intersect, possibly in the future, through namely the [Custom Webapp](https://github.com/YunoHost-Apps/my_webapp_ynh) which specifically is single tenant (the user being called `my_webapp`) and allows one to self-host whatever unpackaged web application they desire (or a website).
I do understand that they overlap though...

Anyways, I think I will find a way to make site.js somehow fit in my set up :)

Thank you again. Keep on the good work!

**Comment by SmilinBrian** [comment]
Just going to throw in here: I ran across small-tech.org and got excited about Site.js for a personal project - the combination of static site generation with JavaScript ability is intriguing - until I discovered there is no clear path to a hosting service.
That is, if there were a Docker template, or some other fairly standard packaging, I'm sure I could find a hosting service. But, if I understand correctly as it stands, I will have to rent and manage my own Linux server/VPS, which is more than I want to learn.
